### ISSUE TITLE
sendDiscoveryRequest may stop!!!

### ISSUE THREAD

**Issue by ntgr-xhan** [resourcepool/ssdp-client#31]
- Senddiscoveryrequest may stop abnormally because only IOException is caught here, 
but concurrent modificationexception may be thrown  ConcurrentModificationException  because "requests. add" operation is performed in handlepresenceannouncement. 
- requests during loop execution add may be executed, causing requests to be changed.

 In addition, I don't understand why I want to add request in handlepresenceannouncement, which may change the purpose of my program
 
![image](https://user-images.githubusercontent.com/8477015/147261084-4b4b8f16-726c-451e-9764-47a6e25a9525.png)

**Comment by loicortola** [comment]
Hi!
Thanks for the notification. Indeed, wasn't really paying attention to potential concurrent writes.
I have handled a quick fix using a synchronized list as the only concurrent issues we might have should happen between the two single threaded executors in the code.
As for the automatic lookup, makes sense. I've added a new SsdpClientOptions attribute called `lookupAllIncomingAnnouncements`. Default value is true for retrocompatibility.
By using the Options builder method `disableAutoLookup()`, you will be able to have the expected behaviour.

Ships in 2.4.5 :)

**Comment by loicortola** [comment]
Feel free to close the issue when acknowledged ;)

**Comment by ntgr-xhan** [comment]
In fact, I have encountered this concurrency problem. Thank you for solving it.

**Comment by hanxiao34** [comment]
In fact, I have encountered this concurrency problem. Thank you for solving it.

**Comment by hanxiao34** [comment]
Thank you for solving it.
